<a href="https://colab.research.google.com/github/Meena-2001/-IBM-Project-15396-1659598189/blob/main/Pandimeena_R_Assignment_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
s

'Hi there Sam!'

In [ ]:
s = "Hi there Sam!"
s=s.split()
s

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import numpy as np
np.ones(10,dtype='int')*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
add=np.concatenate((a,b))
print(add)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd
a1=pd.Series(np.random.rand(2))
a2=pd.Series(np.random.rand(2))
a3=pd.Series(np.random.rand(2))
df=pd.DataFrame([a1,a2,a3])
df

0         1
0  0.586277  0.468676
1  0.654428  0.971663
2  0.405491  0.437577

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
date=pd.date_range(start='01/01/2023',end='10/02/2023',freq='D')
S=pd.Series(date)
print(S)


0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...    
270   2023-09-28
271   2023-09-29
272   2023-09-30
273   2023-10-01
274   2023-10-02
Length: 275, dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
s1=pd.Series(lists[0])
s2=pd.Series(lists[1])
s3=pd.Series(lists[2])
data=pd.DataFrame([s1,s2,s3])
data

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24